# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeDRIFTHASH <- function(DRIFTValues) {
    .Call(`_regCtsem_computeDRIFTHASH`, DRIFTValues)
}

computeDRIFTHASHExponentials <- function(DRIFTHASH, DRIFTHASHExponentialUnique) {
    .Call(`_regCtsem_computeDRIFTHASHExponentials`, DRIFTHASH, DRIFTHASHExponentialUnique)
}

computeDiscreteCINTs <- function(discreteCINTUnique, DRIFTInverseValues, discreteDRIFTUnique, CINTValues) {
    .Call(`_regCtsem_computeDiscreteCINTs`, discreteCINTUnique, DRIFTInverseValues, discreteDRIFTUnique, CINTValues)
}

computeDiscreteDIFFUSIONs <- function(DRIFTHASHInverse, DIFFUSION, DRIFTHASHExponentialUnique, discreteDIFFUSIONUnique) {
    .Call(`_regCtsem_computeDiscreteDIFFUSIONs`, DRIFTHASHInverse, DIFFUSION, DRIFTHASHExponentialUnique, discreteDIFFUSIONUnique)
}

computeDiscreteDRIFTs <- function(DRIFTValues, discreteDRIFTUnique) {
    .Call(`_regCtsem_computeDiscreteDRIFTs`, DRIFTValues, discreteDRIFTUnique)
}

computeDiscreteTRAITs <- function(discreteDRIFTUnique, discreteTRAITUnique) {
    .Call(`_regCtsem_computeDiscreteTRAITs`, discreteDRIFTUnique, discreteTRAITUnique)
}

computeGroupM2LL <- function(sampleSize, nObservedVariables, observedMeans, observedCov, expectedMeans, expectedCovariance) {
    .Call(`_regCtsem_computeGroupM2LL`, sampleSize, nObservedVariables, observedMeans, observedCov, expectedMeans, expectedCovariance)
}

computeIndividualM2LL <- function(nObservedVariables, rawData, expectedMeans, expectedCovariance) {
    .Call(`_regCtsem_computeIndividualM2LL`, nObservedVariables, rawData, expectedMeans, expectedCovariance)
}

computeKalmanLatentCovariancePrediction <- function(discreteDRIFTValues, previousCovariances, discreteDIFFUSIONValues) {
    .Call(`_regCtsem_computeKalmanLatentCovariancePrediction`, discreteDRIFTValues, previousCovariances, discreteDIFFUSIONValues)
}

computeKalmanLatentStatePrediction <- function(discreteDRIFTValues, previousStates, discreteCINTValues) {
    .Call(`_regCtsem_computeKalmanLatentStatePrediction`, discreteDRIFTValues, previousStates, discreteCINTValues)
}

computeKalmanManifestCovariancePrediction <- function(LAMBDA, predictedLatentCovariances, currentMANIFESTVAR) {
    .Call(`_regCtsem_computeKalmanManifestCovariancePrediction`, LAMBDA, predictedLatentCovariances, currentMANIFESTVAR)
}

computeKalmanManifestPrediction <- function(LAMBDAValues, predictedStates, MANIFESTMEANSValues) {
    .Call(`_regCtsem_computeKalmanManifestPrediction`, LAMBDAValues, predictedStates, MANIFESTMEANSValues)
}

computeRAMExpectedCovariance <- function(F, A, S) {
    .Call(`_regCtsem_computeRAMExpectedCovariance`, F, A, S)
}

computeRAMExpectedMeans <- function(F, A, M) {
    .Call(`_regCtsem_computeRAMExpectedMeans`, F, A, M)
}

computeRAMM2LL <- function(RAMdata, expectedMeans, expectedCovariance) {
    .Call(`_regCtsem_computeRAMM2LL`, RAMdata, expectedMeans, expectedCovariance)
}

deepCopyNumericVector <- function(x) {
    .Call(`_regCtsem_deepCopyNumericVector`, x)
}

deepCopyNumericMatrix <- function(x) {
    .Call(`_regCtsem_deepCopyNumericMatrix`, x)
}

deepCopyStringVector <- function(x) {
    .Call(`_regCtsem_deepCopyStringVector`, x)
}

deepCopyStringMatrix <- function(x) {
    .Call(`_regCtsem_deepCopyStringMatrix`, x)
}

deepCopyList <- function(x) {
    .Call(`_regCtsem_deepCopyList`, x)
}

deepCopyDataFrame <- function(x) {
    .Call(`_regCtsem_deepCopyDataFrame`, x)
}

fillA <- function(A, hasDiscreteDRIFTUnique, discreteDRIFTUnique, hasDiscreteTRAITUnique, discreteTRAITUnique, LAMBDA, AParameterIndicators) {
    .Call(`_regCtsem_fillA`, A, hasDiscreteDRIFTUnique, discreteDRIFTUnique, hasDiscreteTRAITUnique, discreteTRAITUnique, LAMBDA, AParameterIndicators)
}

fillM <- function(M, T0MEANS, MANIFESTMEANS, hasDiscreteCINTUnique, discreteCINTUnique, cppMParameterIndicators) {
    .Call(`_regCtsem_fillM`, M, T0MEANS, MANIFESTMEANS, hasDiscreteCINTUnique, discreteCINTUnique, cppMParameterIndicators)
}

fillS <- function(S, T0VAR, MANIFESTVAR, hasDiscreteTRAITUnique, TRAITVAR, hasDiscreteDIFFUSIONUnique, discreteDIFFUSIONUnique, SParameterIndicators) {
    .Call(`_regCtsem_fillS`, S, T0VAR, MANIFESTVAR, hasDiscreteTRAITUnique, TRAITVAR, hasDiscreteDIFFUSIONUnique, discreteDIFFUSIONUnique, SParameterIndicators)
}

getMatrixExponential <- function(mat) {
    .Call(`_regCtsem_getMatrixExponential`, mat)
}

getVarianceFromVarianceBase <- function(varianceBaseValues) {
    .Call(`_regCtsem_getVarianceFromVarianceBase`, varianceBaseValues)
}

kalmanFit <- function(sampleSize, Tpoints, nlatent, nmanifest, kalmanData, latentScores, predictedManifestValues, discreteTimeParameterNames, T0MEANSValues, T0VARValues, discreteDRIFTUnique, discreteCINTUnique, discreteTRAITUnique, discreteDIFFUSIONUnique, LAMBDAValues, MANIFESTMEANSValues, MANIFESTVARValues) {
    .Call(`_regCtsem_kalmanFit`, sampleSize, Tpoints, nlatent, nmanifest, kalmanData, latentScores, predictedManifestValues, discreteTimeParameterNames, T0MEANSValues, T0VARValues, discreteDRIFTUnique, discreteCINTUnique, discreteTRAITUnique, discreteDIFFUSIONUnique, LAMBDAValues, MANIFESTMEANSValues, MANIFESTVARValues)
}

