# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' armaExpmat
#'
#' Computes the matrix exponential using RcppArmadillo
#' @param m symmetric matrix for which the matrix exponential should be computed
#' @returns matrix
armaExpmat <- function(m) {
    .Call('_regCtsem_armaExpmat', PACKAGE = 'regCtsem', m)
}

#' computeDRIFTHASH
#'
#' Computes the computeDRIFTHASH given the drift. DRIFTHASH = DRIFT otimes I + I otimes DRIFT.
#'
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#'
#' @param DRIFTValues matrix with drift values
#' @returns matrix with drift hash
#'
#' @keywords internal
computeDRIFTHASH <- function(DRIFTValues) {
    .Call('_regCtsem_computeDRIFTHASH', PACKAGE = 'regCtsem', DRIFTValues)
}

#' computeDRIFTHASHExponentials
#'
#' Computes the DRIFTHASHExponential for the discrete time diffusion given the drifthash and DRIFTHASHExponential (list with discrete trait names, dTs and results)
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param DRIFTHASH matrix with drift hash
#' @param DRIFTHASHExponentialUnique list with discrete trait names, dTs and results
#' @returns list with drift hash exponentials
#' @keywords internal
computeDRIFTHASHExponentials <- function(DRIFTHASH, DRIFTHASHExponentialUnique) {
    .Call('_regCtsem_computeDRIFTHASHExponentials', PACKAGE = 'regCtsem', DRIFTHASH, DRIFTHASHExponentialUnique)
}

#' computeDiscreteCINTs
#'
#' Computes the discrete time latent intercept values (list with discreteCINT-names, dTs and results) given the inverse of the drift (DRIFTInverseValues), the discreteDRIFTUnique (list with discreteDRIFT-names, dTs and results) and CINTValues
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param discreteCINTUnique list with unique discrete continuous-time-intercepts
#' @param DRIFTInverseValues matrix with inverse of drift values
#' @param discreteDRIFTUnique list with unique discrete drifts
#' @param CINTValues continuous time intercepts
#' @returns list with updated discrete continuous-time-intercepts
#' @keywords internal
computeDiscreteCINTs <- function(discreteCINTUnique, DRIFTInverseValues, discreteDRIFTUnique, CINTValues) {
    .Call('_regCtsem_computeDiscreteCINTs', PACKAGE = 'regCtsem', discreteCINTUnique, DRIFTInverseValues, discreteDRIFTUnique, CINTValues)
}

#' computeDiscreteDIFFUSIONs
#'
#' Computes the discrete time diffusion matrices given the DRIFTHASHInverse, DIFFUSION,
#' DRIFTHASHExponentialUnique (list with expm(drifthash)-names, dTs and results), and discreteDIFFUSIONUnique (list with diffusion-names, dTs and results)
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param DRIFTHASHInverse inverse of drift matrix
#' @param DIFFUSION matrix with diffusion values
#' @param DRIFTHASHExponentialUnique list with expm(drifthash)-names, dTs and results
#' @param discreteDIFFUSIONUnique list with diffusion-names, dTs and results
#' @keywords internal
computeDiscreteDIFFUSIONs <- function(DRIFTHASHInverse, DIFFUSION, DRIFTHASHExponentialUnique, discreteDIFFUSIONUnique) {
    .Call('_regCtsem_computeDiscreteDIFFUSIONs', PACKAGE = 'regCtsem', DRIFTHASHInverse, DIFFUSION, DRIFTHASHExponentialUnique, discreteDIFFUSIONUnique)
}

#' computeDiscreteDRIFTs
#'
#' Computes the discrete time drift matrices given the drift and discreteDRIFTUnique (list with discrete drift names, dTs and results)
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param DRIFTValues matrix with drift values
#' @param discreteDRIFTUnique list with discrete drift names, dTs and results
#' @returns list
#' @keywords internal
computeDiscreteDRIFTs <- function(DRIFTValues, discreteDRIFTUnique) {
    .Call('_regCtsem_computeDiscreteDRIFTs', PACKAGE = 'regCtsem', DRIFTValues, discreteDRIFTUnique)
}

#' computeDiscreteTRAITs
#'
#' Computes the discrete time trait matrices given the discreteDRIFTUnique (list with discrete drift names, dTs and results) and discreteTRAITUnique (list with discrete trait names, dTs and results)
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param discreteDRIFTUnique list with discrete drift names, dTs and results
#' @param discreteTRAITUnique list with discrete trait names, dTs and results
#' @returns list with discrete traits
#' @keywords internal
computeDiscreteTRAITs <- function(discreteDRIFTUnique, discreteTRAITUnique) {
    .Call('_regCtsem_computeDiscreteTRAITs', PACKAGE = 'regCtsem', discreteDRIFTUnique, discreteTRAITUnique)
}

#' computeGroupM2LL
#' Computes the -2log likelihood in a RAM model for a  group of people with identical missing structure given the sample size, number of non-missing variables (nObservedVariables),
#' observedMeans within this sample, observedCov within this sample, filtered expectedMeans, and filtered expectedCovariance.
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#'
#' @param sampleSize number of persons
#' @param nObservedVariables number of observed variables
#' @param observedMeans means of observed variables
#' @param observedCov observed covariance
#' @param expectedMeans expected means
#' @param expectedCovariance expected covariance
#' @returns double
#' @keywords internal
computeGroupM2LL <- function(sampleSize, nObservedVariables, observedMeans, observedCov, expectedMeans, expectedCovariance) {
    .Call('_regCtsem_computeGroupM2LL', PACKAGE = 'regCtsem', sampleSize, nObservedVariables, observedMeans, observedCov, expectedMeans, expectedCovariance)
}

#' computeIndividualM2LL
#'
#' Computes the -2log likelihood in a RAM model for a  single person given the number of non-missing variables (nObservedVariables), x (rawData), filtered expectedMeans, and filtered expectedCovariance.
#' @param nObservedVariables number of non-missing variables
#' @param rawData x
#' @param expectedMeans filtered expectedMeans
#' @param expectedCovariance filtered expectedCovariance
#' @keywords internal
computeIndividualM2LL <- function(nObservedVariables, rawData, expectedMeans, expectedCovariance) {
    .Call('_regCtsem_computeIndividualM2LL', PACKAGE = 'regCtsem', nObservedVariables, rawData, expectedMeans, expectedCovariance)
}

#' computeKalmanLatentCovariancePrediction
#'
#' Computes the prediction step for the residual covariance matrix of the latent states when using the Kalman filter
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param discreteDRIFTValues discrete drift values
#' @param previousCovariances covariances of previous time point
#' @param discreteDIFFUSIONValues discrete diffusion values
#' @returns predicted covariance
#' @keywords internal
computeKalmanLatentCovariancePrediction <- function(discreteDRIFTValues, previousCovariances, discreteDIFFUSIONValues) {
    .Call('_regCtsem_computeKalmanLatentCovariancePrediction', PACKAGE = 'regCtsem', discreteDRIFTValues, previousCovariances, discreteDIFFUSIONValues)
}

#' computeKalmanLatentStatePrediction
#' Computes the prediction step for the latent states when using the Kalman filter
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param discreteDRIFTValues discrete drift values
#' @param previousStates states of previous time point
#' @param discreteCINTValues discrete continuous-time-intercept values
#' @returns vector with predicted states
#' @keywords internal
computeKalmanLatentStatePrediction <- function(discreteDRIFTValues, previousStates, discreteCINTValues) {
    .Call('_regCtsem_computeKalmanLatentStatePrediction', PACKAGE = 'regCtsem', discreteDRIFTValues, previousStates, discreteCINTValues)
}

#' computeKalmanManifestCovariancePrediction
#'
#' Computes the predicted manifest residual covariance matrix given the latent residual covariance when using the Kalman filter
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param LAMBDA loadings matrix
#' @param predictedLatentCovariances predicted latent covariances
#' @param currentMANIFESTVAR current manifest covariance
#' @keywords internal
computeKalmanManifestCovariancePrediction <- function(LAMBDA, predictedLatentCovariances, currentMANIFESTVAR) {
    .Call('_regCtsem_computeKalmanManifestCovariancePrediction', PACKAGE = 'regCtsem', LAMBDA, predictedLatentCovariances, currentMANIFESTVAR)
}

#' computeKalmanManifestPrediction
#'
#' Computes the Prediction for the manifest variables given the predicted latent states when using the Kalman filter
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param LAMBDAValues matrix with loadings
#' @param predictedStates vector with predicted latent states
#' @param MANIFESTMEANSValues vector with means of manifest variables
#' @returns predicted manifest values
#' @keywords internal
computeKalmanManifestPrediction <- function(LAMBDAValues, predictedStates, MANIFESTMEANSValues) {
    .Call('_regCtsem_computeKalmanManifestPrediction', PACKAGE = 'regCtsem', LAMBDAValues, predictedStates, MANIFESTMEANSValues)
}

#' computeRAMExpectedCovariance
#'
#' Computes the expected covariance in a RAM model give filter matrix F, directed effects matrix A, and covariance matrix S.
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param F filter matrix
#' @param A direct effects matrix
#' @param S undirected effects matrix
#' @returns matrix with model implied covariance
#' @keywords internal
computeRAMExpectedCovariance <- function(F, A, S) {
    .Call('_regCtsem_computeRAMExpectedCovariance', PACKAGE = 'regCtsem', F, A, S)
}

#' computeRAMExpectedMeans
#'
#' Computes the expected means in a RAM model give filter matrix F, directed effects matrix A, and means vector M.
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param F filter matrix F
#' @param A matrix with directed effects
#' @param M vector with means
#' @returns matrix with implied means
#' @keywords internal
computeRAMExpectedMeans <- function(F, A, M) {
    .Call('_regCtsem_computeRAMExpectedMeans', PACKAGE = 'regCtsem', F, A, M)
}

#' computeRAMM2LL
#'
#' Computes the -2 log Likelihood
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param RAMdata list with data set
#' @param expectedMeans vector with model implied means
#' @param expectedCovariance matrix with model implied covariance
#' @returns double
#' @keywords internal
computeRAMM2LL <- function(RAMdata, expectedMeans, expectedCovariance) {
    .Call('_regCtsem_computeRAMM2LL', PACKAGE = 'regCtsem', RAMdata, expectedMeans, expectedCovariance)
}

#' deepCopyNumericVector
#'
#' deep copy of Rcpp data
#' @param x Rcpp NumericVector
#' @returns copy of Rcpp NumericVector
#' @keywords internal
deepCopyNumericVector <- function(x) {
    .Call('_regCtsem_deepCopyNumericVector', PACKAGE = 'regCtsem', x)
}

#' deepCopyNumericMatrix
#'
#' deep copy of Rcpp data
#' @param x Rcpp NumericMatrix
#' @returns copy of Rcpp NumericMatrix
#' @keywords internal
deepCopyNumericMatrix <- function(x) {
    .Call('_regCtsem_deepCopyNumericMatrix', PACKAGE = 'regCtsem', x)
}

#' deepCopyStringVector
#'
#' deep copy of Rcpp data
#' @param x Rcpp StringVector
#' @returns copy of Rcpp StringVector
#' @keywords internal
deepCopyStringVector <- function(x) {
    .Call('_regCtsem_deepCopyStringVector', PACKAGE = 'regCtsem', x)
}

#' deepCopyStringMatrix
#'
#' deep copy of Rcpp data
#' @param x Rcpp StringMatrix
#' @returns copy of Rcpp StringMatrix
#' @keywords internal
deepCopyStringMatrix <- function(x) {
    .Call('_regCtsem_deepCopyStringMatrix', PACKAGE = 'regCtsem', x)
}

#' deepCopyList
#'
#' deep copy of Rcpp data
#' @param x Rcpp List
#' @returns copy of Rcpp List
#' @keywords internal
deepCopyList <- function(x) {
    .Call('_regCtsem_deepCopyList', PACKAGE = 'regCtsem', x)
}

#' deepCopyDataFrame
#'
#' deep copy of Rcpp data
#' @param x Rcpp DataFrame
#' @returns copy of Rcpp DataFrame
#' @keywords internal
deepCopyDataFrame <- function(x) {
    .Call('_regCtsem_deepCopyDataFrame', PACKAGE = 'regCtsem', x)
}

#' fillA
#'
#' Fills the A matrix (directed effects) given the A matrix, the discreteDRIFTUnique (list with discrete drift names, dTs and results),
#' discreteTRAITUnique (list with discrete trait names, dTs and results), LAMBDA (loadings), and AParameterIndicators (tells fillA where to put the discreteDRIFT, discreteTRAIT, and LAMBDA)
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param A matrix with directed effects
#' @param hasDiscreteDRIFTUnique boolean
#' @param discreteDRIFTUnique list with discrete drift names, dTs and results
#' @param hasDiscreteTRAITUnique boolean
#' @param discreteTRAITUnique list with discrete trait names, dTs and results
#' @param LAMBDA loadings
#' @param AParameterIndicators tells fillA where to put the discreteDRIFT, discreteTRAIT, and LAMBDA
#' @keywords internal
fillA <- function(A, hasDiscreteDRIFTUnique, discreteDRIFTUnique, hasDiscreteTRAITUnique, discreteTRAITUnique, LAMBDA, AParameterIndicators) {
    .Call('_regCtsem_fillA', PACKAGE = 'regCtsem', A, hasDiscreteDRIFTUnique, discreteDRIFTUnique, hasDiscreteTRAITUnique, discreteTRAITUnique, LAMBDA, AParameterIndicators)
}

#' fillM
#'
#' Fills the M vector (intercepts) given the M vector, the MANIFESTMEANS,
#' discreteCINTUnique (list with discrete continuous time intercepts, dTs and results), and cppMParameterIndicators (tells fillM where to put the MANIFESTMEANS and discreteCINT)
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param M vector with means
#' @param T0MEANS vector with initial means
#' @param MANIFESTMEANS manifest means
#' @param hasDiscreteCINTUnique boolean
#' @param discreteCINTUnique list with discrete continuous time intercepts, dTs and results
#' @param cppMParameterIndicators tells fillM where to put the MANIFESTMEANS and discreteCINT
#' @keywords internal
fillM <- function(M, T0MEANS, MANIFESTMEANS, hasDiscreteCINTUnique, discreteCINTUnique, cppMParameterIndicators) {
    .Call('_regCtsem_fillM', PACKAGE = 'regCtsem', M, T0MEANS, MANIFESTMEANS, hasDiscreteCINTUnique, discreteCINTUnique, cppMParameterIndicators)
}

#' fillS
#'
#' Fills the S matrix (covariances) given the S matrix, the discreteDIFFUSIONUnique (list with discrete diffusion names, dTs and results),
#' MANIFESTVAR (manifest variance), and cppSParameterIndicators (tells fillS where to put the discreteDIFFUSIONUnique and MANIFESTVAR)
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param S matrix with undirected effects
#' @param T0VAR matrix with initial covariances
#' @param TRAITVAR trait variance
#' @param hasDiscreteTRAITUnique boolean
#' @param hasDiscreteDIFFUSIONUnique boolean
#' @param discreteDIFFUSIONUnique list with discrete diffusion names, dTs and results
#' @param MANIFESTVAR manifest variance
#' @param SParameterIndicators tells fillS where to put the discreteDIFFUSIONUnique and MANIFESTVAR
#'
fillS <- function(S, T0VAR, MANIFESTVAR, hasDiscreteTRAITUnique, TRAITVAR, hasDiscreteDIFFUSIONUnique, discreteDIFFUSIONUnique, SParameterIndicators) {
    .Call('_regCtsem_fillS', PACKAGE = 'regCtsem', S, T0VAR, MANIFESTVAR, hasDiscreteTRAITUnique, TRAITVAR, hasDiscreteDIFFUSIONUnique, discreteDIFFUSIONUnique, SParameterIndicators)
}

#' getVarianceFromVarianceBase
#'
#' Computes the covariance matrix given the covariancebase
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param varianceBaseValues matrix with base values
#' @keywords internal
getVarianceFromVarianceBase <- function(varianceBaseValues) {
    .Call('_regCtsem_getVarianceFromVarianceBase', PACKAGE = 'regCtsem', varianceBaseValues)
}

#' kalmanFit
#'
#' Performs the prediction and updating step for the Kalman Filter
#' The implementation closely follows that of Driver, C. C., Oud, J. H. L., & Voelkle, M. C. (2017). Continuous Time Structural Equation Modelling With R Package ctsem. Journal of Statistical Software, 77(5), 1–36. https://doi.org/10.18637/jss.v077.i05
#' @param update boolean
#' @param sampleSize number of persons
#' @param Tpoints number of time points
#' @param nlatent number of latent variables
#' @param nmanifest number of manifest variables
#' @param kalmanData data for Kalman filter
#' @param latentScores matrix with latent scores
#' @param predictedManifestValues matrix with manifest predictions
#' @param discreteTimeParameterNames names of discrete time paramters
#' @param T0MEANSValues vector with initial means
#' @param T0VARValues matrix with initial variances
#' @param discreteDRIFTUnique list with discrete drift values
#' @param discreteCINTUnique list with discrete continuous time intercepts
#' @param discreteTRAITUnique list with discrete traits
#' @param discreteDIFFUSIONUnique list with discrete diffusions
#' @param LAMBDAValues matrix with loadings
#' @param MANIFESTMEANSValues manifest means
#' @param MANIFESTVARValues manifest variance
#' @keywords internal
kalmanFit <- function(update, sampleSize, Tpoints, nlatent, nmanifest, kalmanData, latentScores, predictedManifestValues, discreteTimeParameterNames, T0MEANSValues, T0VARValues, discreteDRIFTUnique, discreteCINTUnique, discreteTRAITUnique, discreteDIFFUSIONUnique, LAMBDAValues, MANIFESTMEANSValues, MANIFESTVARValues) {
    .Call('_regCtsem_kalmanFit', PACKAGE = 'regCtsem', update, sampleSize, Tpoints, nlatent, nmanifest, kalmanData, latentScores, predictedManifestValues, discreteTimeParameterNames, T0MEANSValues, T0VARValues, discreteDRIFTUnique, discreteCINTUnique, discreteTRAITUnique, discreteDIFFUSIONUnique, LAMBDAValues, MANIFESTMEANSValues, MANIFESTVARValues)
}

