# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the computeDRIFTHASH given the drift. DRIFTHASH = DRIFT otimes I + I otimes DRIFT.
#'
#' @export
computeDRIFTHASH <- function(DRIFTValues) {
    .Call('_regCtsem_computeDRIFTHASH', PACKAGE = 'regCtsem', DRIFTValues)
}

computeDRIFTHASHExponentials <- function(DRIFTHASH, DRIFTHASHExponentialUnique) {
    .Call('_regCtsem_computeDRIFTHASHExponentials', PACKAGE = 'regCtsem', DRIFTHASH, DRIFTHASHExponentialUnique)
}

computeDiscreteCINTs <- function(discreteCINTUnique, DRIFTInverseValues, discreteDRIFTUnique, CINTValues) {
    .Call('_regCtsem_computeDiscreteCINTs', PACKAGE = 'regCtsem', discreteCINTUnique, DRIFTInverseValues, discreteDRIFTUnique, CINTValues)
}

computeDiscreteDIFFUSIONs <- function(DRIFTHASHInverse, DIFFUSION, DRIFTHASHExponentialUnique, discreteDIFFUSIONUnique) {
    .Call('_regCtsem_computeDiscreteDIFFUSIONs', PACKAGE = 'regCtsem', DRIFTHASHInverse, DIFFUSION, DRIFTHASHExponentialUnique, discreteDIFFUSIONUnique)
}

computeDiscreteDRIFTs <- function(DRIFTValues, discreteDRIFTUnique) {
    .Call('_regCtsem_computeDiscreteDRIFTs', PACKAGE = 'regCtsem', DRIFTValues, discreteDRIFTUnique)
}

computeDiscreteTRAITs <- function(discreteDRIFTUnique, discreteTRAITUnique) {
    .Call('_regCtsem_computeDiscreteTRAITs', PACKAGE = 'regCtsem', discreteDRIFTUnique, discreteTRAITUnique)
}

computeGroupM2LL <- function(sampleSize, nObservedVariables, observedMeans, observedCov, expectedMeans, expectedCovariance) {
    .Call('_regCtsem_computeGroupM2LL', PACKAGE = 'regCtsem', sampleSize, nObservedVariables, observedMeans, observedCov, expectedMeans, expectedCovariance)
}

computeIndividualM2LL <- function(nObservedVariables, rawData, expectedMeans, expectedCovariance) {
    .Call('_regCtsem_computeIndividualM2LL', PACKAGE = 'regCtsem', nObservedVariables, rawData, expectedMeans, expectedCovariance)
}

computeKalmanLatentCovariancePrediction <- function(discreteDRIFTValues, previousCovariances, discreteDIFFUSIONValues) {
    .Call('_regCtsem_computeKalmanLatentCovariancePrediction', PACKAGE = 'regCtsem', discreteDRIFTValues, previousCovariances, discreteDIFFUSIONValues)
}

computeKalmanLatentStatePrediction <- function(discreteDRIFTValues, previousStates, discreteCINTValues) {
    .Call('_regCtsem_computeKalmanLatentStatePrediction', PACKAGE = 'regCtsem', discreteDRIFTValues, previousStates, discreteCINTValues)
}

computeKalmanManifestCovariancePrediction <- function(LAMBDA, predictedLatentCovariances, currentMANIFESTVAR) {
    .Call('_regCtsem_computeKalmanManifestCovariancePrediction', PACKAGE = 'regCtsem', LAMBDA, predictedLatentCovariances, currentMANIFESTVAR)
}

computeKalmanManifestPrediction <- function(LAMBDAValues, predictedStates, MANIFESTMEANSValues) {
    .Call('_regCtsem_computeKalmanManifestPrediction', PACKAGE = 'regCtsem', LAMBDAValues, predictedStates, MANIFESTMEANSValues)
}

computeRAMExpectedCovariance <- function(F, A, S) {
    .Call('_regCtsem_computeRAMExpectedCovariance', PACKAGE = 'regCtsem', F, A, S)
}

computeRAMExpectedMeans <- function(F, A, M) {
    .Call('_regCtsem_computeRAMExpectedMeans', PACKAGE = 'regCtsem', F, A, M)
}

computeRAMM2LL <- function(RAMdata, expectedMeans, expectedCovariance) {
    .Call('_regCtsem_computeRAMM2LL', PACKAGE = 'regCtsem', RAMdata, expectedMeans, expectedCovariance)
}

deepCopyNumericVector <- function(x) {
    .Call('_regCtsem_deepCopyNumericVector', PACKAGE = 'regCtsem', x)
}

deepCopyNumericMatrix <- function(x) {
    .Call('_regCtsem_deepCopyNumericMatrix', PACKAGE = 'regCtsem', x)
}

deepCopyStringVector <- function(x) {
    .Call('_regCtsem_deepCopyStringVector', PACKAGE = 'regCtsem', x)
}

deepCopyStringMatrix <- function(x) {
    .Call('_regCtsem_deepCopyStringMatrix', PACKAGE = 'regCtsem', x)
}

deepCopyList <- function(x) {
    .Call('_regCtsem_deepCopyList', PACKAGE = 'regCtsem', x)
}

deepCopyDataFrame <- function(x) {
    .Call('_regCtsem_deepCopyDataFrame', PACKAGE = 'regCtsem', x)
}

fillA <- function(A, hasDiscreteDRIFTUnique, discreteDRIFTUnique, hasDiscreteTRAITUnique, discreteTRAITUnique, LAMBDA, AParameterIndicators) {
    .Call('_regCtsem_fillA', PACKAGE = 'regCtsem', A, hasDiscreteDRIFTUnique, discreteDRIFTUnique, hasDiscreteTRAITUnique, discreteTRAITUnique, LAMBDA, AParameterIndicators)
}

fillM <- function(M, T0MEANS, MANIFESTMEANS, hasDiscreteCINTUnique, discreteCINTUnique, cppMParameterIndicators) {
    .Call('_regCtsem_fillM', PACKAGE = 'regCtsem', M, T0MEANS, MANIFESTMEANS, hasDiscreteCINTUnique, discreteCINTUnique, cppMParameterIndicators)
}

fillS <- function(S, T0VAR, MANIFESTVAR, hasDiscreteTRAITUnique, TRAITVAR, hasDiscreteDIFFUSIONUnique, discreteDIFFUSIONUnique, SParameterIndicators) {
    .Call('_regCtsem_fillS', PACKAGE = 'regCtsem', S, T0VAR, MANIFESTVAR, hasDiscreteTRAITUnique, TRAITVAR, hasDiscreteDIFFUSIONUnique, discreteDIFFUSIONUnique, SParameterIndicators)
}

getMatrixExponential <- function(mat) {
    .Call('_regCtsem_getMatrixExponential', PACKAGE = 'regCtsem', mat)
}

getVarianceFromVarianceBase <- function(varianceBaseValues) {
    .Call('_regCtsem_getVarianceFromVarianceBase', PACKAGE = 'regCtsem', varianceBaseValues)
}

kalmanFit <- function(sampleSize, Tpoints, nlatent, nmanifest, kalmanData, latentScores, predictedManifestValues, discreteTimeParameterNames, T0MEANSValues, T0VARValues, discreteDRIFTUnique, discreteCINTUnique, discreteTRAITUnique, discreteDIFFUSIONUnique, LAMBDAValues, MANIFESTMEANSValues, MANIFESTVARValues) {
    .Call('_regCtsem_kalmanFit', PACKAGE = 'regCtsem', sampleSize, Tpoints, nlatent, nmanifest, kalmanData, latentScores, predictedManifestValues, discreteTimeParameterNames, T0MEANSValues, T0VARValues, discreteDRIFTUnique, discreteCINTUnique, discreteTRAITUnique, discreteDIFFUSIONUnique, LAMBDAValues, MANIFESTMEANSValues, MANIFESTVARValues)
}

